<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Forms</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e9a5032e-84e2-4975-888a-a166bcc76e5c</testSuiteGuid>
   <testCaseLink>
      <guid>151770c9-35ed-4c76-b52d-6ef206d28c7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Form_Katalon-RunBySuite</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2bc0a004-968f-4e78-bb58-a8407f66bf73</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/New Test Data 4 _ Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>2bc0a004-968f-4e78-bb58-a8407f66bf73</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>588d5b11-3577-4025-9328-5fb68f5376bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2bc0a004-968f-4e78-bb58-a8407f66bf73</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>be721434-b2fa-4bdb-9b41-9a4ef15aecce</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
