<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_passwordBox</name>
   <tag></tag>
   <elementGuidId>f79c4a38-f335-4a56-8fd1-4e3877bd4b4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>أدخل كلمة سر جديدة </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2NMBWXmwpqTWf-9xP2dD-_ _1LZD8393JLs5BcTKbrMmUW _18Ti-FoR9yWcTVsg3rVP41 </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContainer&quot;)/div[@class=&quot;xeN0kdsLg9h3ooNcc_d5m&quot;]/div[1]/div[@class=&quot;_7enAyYKFAHr3gKkOdnlp_&quot;]/div[@class=&quot;themeWithBgImage-0-119 themeWithBgImage-0-15 RsPzdo6jY-WbSphuF3M76&quot;]/div[1]/div[@class=&quot;WpWwMDnjsk8ZAm-Jua5l-&quot;]/div[@class=&quot;_2clHYhsHg9UWOvB3ZLMQcg fullscreen-0-121 fullscreen-0-17&quot;]/form[@class=&quot;_2M1qo23gVi6E7NKzDukRiK form-0-122 form-0-18 _3DUJrbkXRiaDdBUnBnQe7W _3S24CWnxsYuJhNpMvVMww4 _2S-KbGsr2ywaYQQsYoe5lR&quot;]/div[@class=&quot;IerEoa1t46PV2xI1asc-_&quot;]/div[@class=&quot;_2naHf5b8TdGvIKa7Hxp9sK&quot;]/input[@class=&quot;_2NMBWXmwpqTWf-9xP2dD-_ _1LZD8393JLs5BcTKbrMmUW _18Ti-FoR9yWcTVsg3rVP41&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContainer']/div[3]/div/div[2]/div/div/div/div/form/div[3]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
