<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_emailBox</name>
   <tag></tag>
   <elementGuidId>0d502123-26a3-4ab8-bea0-e34d563bf133</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>البريد الإلكتروني</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2NMBWXmwpqTWf-9xP2dD-_ _1Be6o5SfZF0t2sMiiQhGNh _18Ti-FoR9yWcTVsg3rVP41 </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContainer&quot;)/div[@class=&quot;xeN0kdsLg9h3ooNcc_d5m&quot;]/div[1]/div[@class=&quot;_7enAyYKFAHr3gKkOdnlp_&quot;]/div[@class=&quot;themeWithBgImage-0-119 themeWithBgImage-0-15 RsPzdo6jY-WbSphuF3M76&quot;]/div[1]/div[@class=&quot;WpWwMDnjsk8ZAm-Jua5l-&quot;]/div[@class=&quot;_1KCl1TNt_PhBhMv0MAIWol fullscreen-0-121 fullscreen-0-17&quot;]/div[@class=&quot;formContainer-0-124 formContainer-0-20&quot;]/form[@class=&quot;_3fMpcTsiydOsJsHJc57roT form-0-122 form-0-18 O7ADD6GfWAGrkejfiL6G7 _3vu-mf2CZgqeiZ2UtZ8oOM _3A3IGgR3eCgQoG3P6ZT6qf&quot;]/div[@class=&quot;IerEoa1t46PV2xI1asc-_&quot;]/div[@class=&quot;_2naHf5b8TdGvIKa7Hxp9sK&quot;]/input[@class=&quot;_2NMBWXmwpqTWf-9xP2dD-_ _1Be6o5SfZF0t2sMiiQhGNh _18Ti-FoR9yWcTVsg3rVP41&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContainer']/div[3]/div/div[2]/div/div/div/div/div[2]/form/div[2]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
