<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PromoLink</name>
   <tag></tag>
   <elementGuidId>c251ffa5-e164-40b7-804c-94f0e29258ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainContainer']/div[3]/header/div/div[3]/span/div/div[2]/div[4]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ar/mena-promo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>جرّب شاهد VIP</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContainer&quot;)/div[@class=&quot;xeN0kdsLg9h3ooNcc_d5m&quot;]/header[@class=&quot;_321IHS-_KruVv3UhlqNmy3 _2Ot59GewVsrIG3WBm927hF&quot;]/div[@class=&quot;_2bIdoX5jLyhxWbfE6FnmoO&quot;]/div[@class=&quot;_3mUN66pKTm--rxYiLr5MTO&quot;]/span[@class=&quot;_3Ge2dzNUFFjPo9vX6_sNUa ICwrg1u9zHQVMdEk1K4T5&quot;]/div[@class=&quot;_3J54TvZLp5-KkbZY9N-iT6&quot;]/div[@class=&quot;_28fEORBLHgd1MqP85PlRFU&quot;]/div[@class=&quot;_1XLNLE8SstnB4AsQTYPUi5&quot;]/div[@class=&quot;_1ZBFue7VModJTCOy5_yAOu true _2DicJl-muDgwn4fKXHSSlu _2LHpXNiSP8aHo1ZMxkkiZW&quot;]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContainer']/div[3]/header/div/div[3]/span/div/div[2]/div[4]/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الدخول'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مباشر'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ar/mena-promo')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/a</value>
   </webElementXpaths>
</WebElementEntity>
